### ISSUE TITLE
Update to 1.0.0

### ISSUE THREAD

**Issue by ricardo-rp** [sergiodxa/swr-mutate-many#258]
This package is very good. There is not a simple way in the nextjs docs to do what this package does for swr 1.0.0. I would like to ask you to kindly update it to work with version 1.0.0

**Comment by Rednegniw** [comment]
I second this! @sergiodxa

**Comment by sergiodxa** [comment]
If someone wants to send a PR to update it I can take a look and do a release, but since I’m not using SWR anymore I don’t have time or experience with v1 to update it
